name:                cyk-parser
version:             0.1.0.0
github:              "joom/cyk-parser"
license:             MIT
author:              "Joomy Korkut"
maintainer:          "joomy@cs.princeton.edu"
copyright:           "2023 Joomy Korkut"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joom/cyk-parser#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- aeson
- aeson-pretty
- hashtables >= 1.3 && < 2
- optparse-applicative >= 0.17.0.0 && < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cyk-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cyk-parser
